### ISSUE TITLE
ImportError: libjpeg.so.8: 

### ISSUE THREAD

**Issue by marqh** [conda-forge/python-ecmwf_grib-feedstock#6] opened 2016-07-15 15:54 UTC
Hi @ocefpaf et al

I have a confusing issue.

If i conda install this package on my local fedora box, then `import gribapi` works fine

however, if I run a build of a new package, which uses this package, the I get import errors:

```
ImportError: libjpeg.so.8: cannot open shared object file: No such file or directory
```

https://github.com/SciTools/conda-recipes-scitools/pull/174

have you any clues why this might be happening and what I can do?

thank you
mark

**Comment by ocefpaf** [comment] 2016-07-15 16:08
@marqh that has been plaguing us for a while. The problem is that we have a few moving parts here and  makes it complicated to use the default channel and `conda-forge` together.

In conda-forge we use (and pin) everything to `jpeg 9*`, but in `defaults` they use (but don't always pin) to `jpeg 8*`. My guess is that you got some package from `defaults` for some reason. We need to find that reason and here is what we can try:
- Latest conda has a channel preference feature. So update your conda and be sure to have the `conda-forge` channel on top of `defaults` in your `.condarc` file. Then try again in a clean env.
- If the failure persists send us the results of `conda info` and `conda list` so we can investigate what (and hopefully why) the solver is getting something compiled against `jpeg 8*`.

**Comment by ocefpaf** [comment] 2016-07-25 12:22
I cannot reproduce this when I add conda-forge on top on `defaults`. It does not mean that this is gone b/c depending on the combination of packages one is installing conda is known to break the pinning sometimes and causing grieve. Closing this as there is nothing we can do, but let me know if this is still a problem for you.

**Closed as completed by ocefpaf** 2016-07-25 12:22 UTC
