### ISSUE TITLE
ImportError: libhdf5.so.10

### ISSUE THREAD

**Issue by djkirkham** [conda-forge/python-ecmwf_grib-feedstock#25] opened 2017-11-23 17:27 UTC
I receive the following error when I try to import gribapi:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../miniconda2/envs/newgrib/lib/python2.7/site-packages/gribapi/__init__.py", line 1, in <module>
    from .gribapi import *                # noqa
  File ".../miniconda2/envs/newgrib/lib/python2.7/site-packages/gribapi/gribapi.py", line 31, in <module>
    import gribapi_swig as _internal
  File ".../miniconda2/envs/newgrib/lib/python2.7/site-packages/gribapi/gribapi_swig.py", line 25, in <module>
    _gribapi_swig = swig_import_helper()
  File ".../miniconda2/envs/newgrib/lib/python2.7/site-packages/gribapi/gribapi_swig.py", line 21, in swig_import_helper
    _mod = imp.load_module('_gribapi_swig', fp, pathname, description)
ImportError: libhdf5.so.10: cannot open shared object file: No such file or directory
```

I have hdf5 version 1.10.1 in my environment.

If I locate `_gribapi_swig.so`, which I assume is being referred to, and run `ldd` I find that it is looking for both `libhdf5.so.10` and `libhdf5.so.101` (which it can locate).

**Comment by ocefpaf** [comment] 2017-11-23 17:47
@djkirkham I just tried:

```
conda create --yes --name TEST  python-ecmwf_grib --channel conda-forge
source activate TEST
python -c 'import gribapi; print(gribapi.__version__)'
1.23.1
```

and everything worked for me. Can you ensure that `conda-forge` is on top of `defaults` in your `.condarc` and try to install python-ecmwf_grib in an env like I did above?

If that does not work please paste the results of `conda info -a` and `conda list` for that env.

**Comment by djkirkham** [comment] 2017-11-24 12:27
@ocefpaf Creating the environment using those commands results in the same error. Here are the results of the commands you requested:
```
$ conda info -a
Current conda install:

               platform : linux-64
          conda version : 4.3.29
       conda is private : False
      conda-env version : 4.3.29
    conda-build version : 2.1.17
         python version : 2.7.12.final.0
       requests version : 2.13.0
       root environment : /data/users/dkirkham/miniconda2  (writable)
    default environment : /data/users/dkirkham/miniconda2/envs/TEST
       envs directories : /data/users/dkirkham/miniconda2/envs
                          /home/h02/dkirkham/.conda/envs
          package cache : /data/users/dkirkham/miniconda2/pkgs
                          /home/h02/dkirkham/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/h02/dkirkham/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.29 requests/2.13.0 CPython/2.7.12 Linux/2.6.32-696.13.2.el6.x86_64 Red Hat Enterprise Linux Client/6.9 glibc/2.12    
                UID:GID : 11214:1000
# conda environments:
#
TEST                  *  /data/users/dkirkham/miniconda2/envs/TEST
cartopy-dev              /data/users/dkirkham/miniconda2/envs/cartopy-dev
cartopy-dev-latest       /data/users/dkirkham/miniconda2/envs/cartopy-dev-latest
cartopy-test             /data/users/dkirkham/miniconda2/envs/cartopy-test
esmf                     /data/users/dkirkham/miniconda2/envs/esmf
iris-build               /data/users/dkirkham/miniconda2/envs/iris-build
iris-dev                 /data/users/dkirkham/miniconda2/envs/iris-dev
newgrib                  /data/users/dkirkham/miniconda2/envs/newgrib
oldgrib                  /data/users/dkirkham/miniconda2/envs/oldgrib
root                     /data/users/dkirkham/miniconda2

sys.version: 2.7.12 |Continuum Analytics, Inc.| (defa...
sys.prefix: /data/users/dkirkham/miniconda2
sys.executable: /data/users/dkirkham/miniconda2/bin/python
conda location: /data/users/dkirkham/miniconda2/lib/python2.7/site-packages/conda
conda-build: /home/h02/dkirkham/miniconda2/bin/conda-build
conda-build-all: /home/h02/dkirkham/miniconda2/bin/conda-build-all
conda-buildall: /home/h02/dkirkham/miniconda2/bin/conda-buildall
conda-convert: /home/h02/dkirkham/miniconda2/bin/conda-convert
conda-develop: /home/h02/dkirkham/miniconda2/bin/conda-develop
conda-env: /home/h02/dkirkham/miniconda2/bin/conda-env
conda-execute: /home/h02/dkirkham/miniconda2/bin/conda-execute
conda-gitenv: /home/h02/dkirkham/miniconda2/bin/conda-gitenv
conda-index: /home/h02/dkirkham/miniconda2/bin/conda-index
conda-inspect: /home/h02/dkirkham/miniconda2/bin/conda-inspect
conda-metapackage: /home/h02/dkirkham/miniconda2/bin/conda-metapackage
conda-render: /home/h02/dkirkham/miniconda2/bin/conda-render
conda-server: /home/h02/dkirkham/miniconda2/bin/conda-server
conda-sign: /home/h02/dkirkham/miniconda2/bin/conda-sign
conda-skeleton: /home/h02/dkirkham/miniconda2/bin/conda-skeleton
conda-tmpenv: /home/h02/dkirkham/miniconda2/bin/conda-tmpenv
conda-verify: /home/h02/dkirkham/miniconda2/bin/conda-verify
user site dirs: ~/.local/lib/python2.7
                ~/.local/lib/python3.4
                ~/.local/lib/python3.5
                ~/.local/lib/python3.6

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: TEST
CONDA_ENVS_PATH: <not set>
LD_LIBRARY_PATH: /opt/pgi/linux86-64/11.7/lib:/opt/pgi/linux86-64/11.7/libso:/opt/intel/composerxe-2011.4.191/compiler/lib/intel64:/opt/intel/composerxe-2011.4.191/mpirt/lib/intel64:/opt/ukmo/share/lib
PATH: /data/users/dkirkham/miniconda2/envs/TEST/bin:/home/h02/dkirkham/miniconda2/bin:/usr/local/sci/bin:/opt/pgi/linux86-64/11.7/bin:/opt/NAGWare/5.2/x86_64/bin:/opt/intel/composerxe-2011.4.191/bin/intel64:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/ecaccess-4.0.0/client:/opt/ecaccess/client/tools:/opt/ukmo/idl/ukmo/bin:/opt/moose-client-wrapper/bin:/opt/ukmo/utils/bin:/home/h02/dkirkham/.local/bin:/home/h02/dkirkham/bin:/opt/intel/composerxe-2011.4.191/mpirt/bin/intel64
PYTHONHOME: <not set>
PYTHONPATH: <not set>

WARNING: could not import _license.show_info
# try:
# $ conda install -n root _license

```

```
$ conda list
# packages in environment at /data/users/dkirkham/miniconda2/envs/TEST:
#
ca-certificates           2017.11.5                     0    conda-forge
certifi                   2017.11.5                py27_0    conda-forge
curl                      7.55.1                        0    conda-forge
ecmwf_grib                1.23.1                        1    conda-forge
hdf4                      4.2.13                        0    conda-forge
hdf5                      1.10.1                        1    conda-forge
intel-openmp              2018.0.0             hc7b2577_8    defaults
jasper                    1.900.1                       4    conda-forge
jpeg                      9b                            2    conda-forge
krb5                      1.14.2                        0    conda-forge
libgcc                    7.2.0                h69d50b8_2    defaults
libgcc-ng                 7.2.0                h7cc24e2_2    defaults
libgfortran               3.0.0                         1    defaults
libnetcdf                 4.4.1.1                      10    conda-forge
libpng                    1.6.28                        2    conda-forge
libssh2                   1.8.0                         2    conda-forge
libstdcxx-ng              7.2.0                h7a57d05_2    defaults
mkl                       2018.0.1             h19d6760_4    defaults
ncurses                   5.9                          10    conda-forge
numpy                     1.13.3           py27hbcc08e0_0    defaults
openssl                   1.0.2l                        0    conda-forge
pip                       9.0.1                    py27_0    conda-forge
python                    2.7.14                        1    conda-forge
python-ecmwf_grib         1.23.1                   py27_0    conda-forge
readline                  6.2                           0    conda-forge
setuptools                36.7.2                   py27_0    conda-forge
sqlite                    3.13.0                        1    conda-forge
tk                        8.5.19                        2    conda-forge
wheel                     0.30.0                     py_1    conda-forge
zlib                      1.2.11                        0    conda-forge
```

**Comment by ocefpaf** [comment] 2017-11-24 12:32
We have the exact same packages, the only thing that drew my attention is:

```
user site dirs: ~/.local/lib/python2.7
                ~/.local/lib/python3.4
                ~/.local/lib/python3.5
                ~/.local/lib/python3.6
```

Could that be interfering with what you are seeing?

**Comment by DPeterK** [comment] 2017-12-08 16:23
I was recently able to reproduce this on two separate Linux machines and could not work around it. In both cases it happened whether the conda install was clean or not. I'm sure there's something broken with this build, as the problem was **identical** to that which @djkirkham first reported here.

**Comment by ocefpaf** [comment] 2018-04-17 19:06
Please take a look at the latest release and let me know if you still experience this issue.
Closing this b/c I was unable to reproduce and the package works fine in other deployments :-/

**Closed as completed by ocefpaf** 2018-04-17 19:06 UTC
